version: '3'

services:
  mongodb:
    image: mongo:3.2
    command: mongod
    volumes:
      - mongo-data:/data/db
      - ./mongo-backup:/src/mongo-backup
    ports:
      - "27017:27017"

  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
    - "6379:6379"

  elasticsearch:
    image: udata/elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  udata:
    image: udata/udata
    environment:
      - http_proxy
      - https_proxy
      - no_proxy=127.0.0.1,localhost
    command: serve --host 0.0.0.0 --debugger --reload
    links:
      - mongodb:mongodb
      - redis:redis
      - elasticsearch:elasticsearch
    volumes:
      - ./docker/udata.cfg:/udata/udata.cfg
      - .:/src/gouvlu
      - ./static:/udata/fs
    ports:
      - "7000:7000"

  assets:
    image: node:8.9.1-alpine
    working_dir: /src/
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/src/

volumes:
  udata-fs:
  mongo-data:
  redis-data:
  elasticsearch-data:
